### ISSUE TITLE
Making anonymous signin 'match' regular firebaseui

### ISSUE THREAD

**Issue by dsl101** [firebase/firebaseui-web#288] opened 2018-01-12 12:30 UTC
Not having an 'anonymous' provider in firebaseui seems to make offering anonymous signin as a separate button problematic. Firstly, styling the button so it exactly matches what is rendered in the widget is hard. But secondly, the flow—render ui, redirect to google to process, e.g. account chooser and login, then back to ui—means when the user is returned to the original login page, the sign in anonymously button is still shown even though the firebaseui widget now just shows the progress scroller.

I couldn't see any callbacks to show which part of the sign-in process we're at, and `uiShown()` is called on both occasions, even though the login buttons are only shown the first time round. I tried looking for some property of the ui object to infer the step in the process, but it doesn't look like it's really designed for client side code.

Could you explain what the preferred markup is for integrating anonymous signin? Or perhaps there is some justification here for adding the option of an 'anonymous' provider to make this user experience more consistent?

Many thanks for any advice!

**Comment by bojeil-google** [comment] 2018-01-12 20:14
Hey @dsl101, to solve your first problem, we were planning on adding in the next couple of weeks a new API `ui.isPendingRedirect()` which tells you before rendering FirebaseUI whether there is a pending redirect operation (whether user is signing in with redirect or going through account chooser). If that is true, then you can hide the `Sign in as guest` button when rendering the UI.

We don't provide a `Sign in as guest` button as many developers usually `signInAnonymously` on app launch and we are also working on providing the ability to upgrade anonymous user via FirebaseUI. In that case, the button wouldn't make sense. Other developers present the button separately and use the UI to sign in as non-guest.

`uiShown` is triggered on the first UI shown. It is useful to show something like a loading text, etc. before the UI is displayed. 
You could use the callback `uiChanged`:
```
// Do not manipulate FirebaseUI DOM as it will break it.
'uiChanged': function(fromPageId, toPageId) {
  // if toPageId is nascar page, show sign in as guest button.
  // else hide that button.
}
```
You should only use this for displaying things **around the UI** and **not touch the internal FirebaseUI DOM** as you could break it and as this content is subject to change. Also as this is not an official API, it may go away in the future. So keep that in mind.

We can look into providing the ability to add sign in buttons for providers that Firebase Auth doesn't support via some callbacks. This could be possibly used for custom authentication or anonymous sign-in. We can look into whether we should add a dedicated anonymous sign in option in FirebaseUI.

**Comment by dsl101** [comment] 2018-01-16 15:56
Thanks for the detailed reply! `.isPendingRedirect()` sounds like it will be useful for hiding the additional button. From a styling point of view though, I still think it would be much better if it was part of the main UI, and since the call is simply `firebase.auth().signInAnonymously()`, it doesn't seem like it would really add any extra weight to firebaseUI. It could be set up like this:
```
  const ui = new firebaseui.auth.AuthUI(firebase.auth())
  ui.start('#firebaseui-auth-container', {
    signInSuccessUrl: this.redirect,
    signInOptions: [
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      firebase.auth.EmailAuthProvider.PROVIDER_ID,
      ui.ANONYMOUS_PROVIDER_ID
    ]
  })
```
and if someone _doesn't_ want the button because, as you say, they automatically log people in anonymously, they simply wouldn't include that last constant in the options (I just made that up—I guess it could be done differently with a named options like `showAnonymousLogin: false` or something).

For our app, we want people to make a choice about login, not automatically log them in, and currently it's hard to replicate the exact look of the widget buttons in our own code.

**Comment by bojeil-google** [comment] 2018-01-16 18:10
I understand and we will look into it. The information I provided in my earlier reply should unblock you and give you all the tools needed to build this on your own.

**Comment by bojeil-google** [comment] 2018-01-18 17:43
Sounds good. We'll keep you posted once we make a decision on this.

**Comment by dsl101** [comment] 2018-01-25 17:05
Sorry, I'm not seeing the `uiChanged()` callback being fired at all. I do see the `uiShown()` callback. This is the code I'm using to start the ui:
```
      ui.start('#firebaseui-auth-container', {
        callbacks: {
          'uiChanged': function (fromPageId, toPageId) {
            console.log('uiChanged fromPageId:', fromPageId)
            console.log('uiChanged toPageId:', toPageId)
          },
          'uiShown': function () {
            console.log('uiShown')
          }
        },
        signInSuccessUrl: this.redirect,
        signInOptions: [
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID
        ]
      })
```
Has that callback gone already?

**Comment by bojeil-google** [comment] 2018-01-25 18:29
At first glance, it looks like an obfuscation bug. As, this is not an officially supported API, we never really tested it in production. I will get a fix out in the coming week.

**Comment by dsl101** [comment] 2018-01-25 18:30
Great - many thanks.

**Comment by bojeil-google** [comment] 2018-02-06 00:51
This should be fixed in 2.6.0:
https://github.com/firebase/firebaseui-web/releases/tag/v2.6.0

Please re-open this issue if you discover otherwise.

**Closed by bojeil-google** 2018-02-06 00:51 UTC

**Comment by dsl101** [comment] 2018-02-06 10:29
Well, it might just be lack of full docs on how to use this, but this is my code, just for testing how to react to the events / status:
```
      ui.start('#firebaseui-auth-container', {
        callbacks: {
          'uiChanged': function (fromPageId, toPageId) {
            console.log('uiChanged isPendingRedirect: ', ui.isPendingRedirect())
            console.log('uiChanged fromPageId:', fromPageId)
            console.log('uiChanged toPageId:', toPageId)
          },
          'uiShown': function (x) {
            console.log('uiShown isPendingRedirect: ', ui.isPendingRedirect())
          }
        },
        signInSuccessUrl: this.redirect,
        signInOptions: [
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID
        ]
      })
```

And this is the resulting console output. Note there's no apparent difference in the `uiChanged()` logging statements. pre- and post-redirect, and `isPendingRedirect()` always returns false.

![image](https://user-images.githubusercontent.com/900542/35854526-78369b8e-0b28-11e8-9dd3-7f10b37c8711.png)


I can _infer_ whether to show my anonymous login button by looking for `providerSignIn` as the value of the `toPageId` parameter in `uiChanged()`, but this seems not quite as expected...

**Comment by bojeil-google** [comment] 2018-02-06 18:04
I think you are misusing `isPendingRedirect`. After you render the UI, it will typically return false. This API is used commonly if you have a single page app where you show the sign-in UI on the same page, conditionally, when a user clicks a button or navigates to some page dynamically (without a real URL redirect). When you come back to the page (after signing in with Google), you can't tell if you need to show the sign-in UI for sign-in completion. This is why you check that value and if it is true, render firebaseui.

**Comment by dsl101** [comment] 2018-02-08 09:32
I _think_ that's why I'm trying to do. This is from a SPA using Vue and Quasar framework. The URL of the login page is /login, and the provided redirect URL is wherever the user was originally trying to go which required authentication (e.g. /events). But those are both handled by the same client code—there is no actual navigation.

The first 3 'Navigated to' entries in the log are from firebaseUI opening e.g. AccountChooser, and presumable the firebase entries are from that authentication provider. The 4th is back to where we started at /login, which is my SPA.

Can you explain further or give any example code of how an SPA _should_ use `isPendingRedirect`?

**Comment by bojeil-google** [comment] 2018-02-08 17:59
Not sure how much more I can explain this.
You only call `isPendingRedirect` before rendering `firebaseUI` if you only render the UI conditionally. Calling it after UI is rendered will always return false.
```
var ui = new firebaseui.auth.AuthUI(auth);
// Is there a pending redirect that is waiting processing?
if (ui.isPendingRedirect()) {
  ui.start('#firebaseui-auth-container', uiConfig);
}
```

**Comment by dsl101** [comment] 2018-02-09 09:53
No, that's what I was missing. I thought you had to call ui.start before accessing any of the other APIs. That makes sense now.

**Comment by dsl101** [comment] 2018-02-09 11:17
Actually, in my case (not sure where you _wouldn't_ want to do this?), it's not `ui.start()` which needs guarding, as I need to call it first time round to show the login buttons, and on redirect to process the login. It's the anonymous button which should be _hidden_ when the page is loaded and `isisPendingRedirect()` is `true`, but that must be tested _before_ calling `ui.start()`.

**Comment by bojeil-google** [comment] 2018-02-09 18:02
When you return to the page and `isPendingRedirect()` is true, you render the UI, provider sign in screen should not show unless some error occurs.

**Comment by dsl101** [comment] 2018-02-10 09:14
Yes, it's working fine now. It's just that your example code above might suggest that you _only_ call `ui.start()` if `isPendingRedirect()` returns `true`. I just wanted to clarify that you almost certainly want to call `ui.start()` regardless (first to show the buttons, and second to process the request). My code is now kind of like this:
```
var ui = new firebaseui.auth.AuthUI(auth);
// Is there a pending redirect that is waiting processing?
if (ui.isPendingRedirect()) {
  hideAnonymousSignin();  // So the user doesn't see the anonymous button when the login is being processed
}
ui.start('#firebaseui-auth-container', uiConfig);
```

**Comment by bojeil-google** [comment] 2018-02-10 23:06
I don't understand what you are doing.
The issue is that you want to show the sign in as guest button only in the provider sign in page. That should not show on redirect back from OAuth sign-in or accountchooser.com.  If there is a pending redirect and you render the UI, it shouldn't show the provider sign in page, as far as I can remember.

**Comment by dsl101** [comment] 2018-02-11 10:12
Yes, you're right, and all is sorted now. My previous post was just to point out that I (and others with a similar flow) need to call `ui.start()` _regardless_ of the value of `ui.isPendingRedirect()`. The first time it shows the provider buttons, the second time (on redirect) it processes the login. Your post [here](https://github.com/firebase/firebaseui-web/issues/288#issuecomment-364195862) suggested only calling it if `ui.isPendingRedirect()` returned `true`, which meant the provider buttons would never be shown in the first place. That's all I was clarifying. Many thanks for your help.

**Comment by Bus42** [comment] 2018-09-26 02:05
Noticed the issue was closed, but thought I'd add that I would really like to see a 'Continue as Guest' option or something similar on the redirects and popups for authentication as well.

**Comment by wti806** [comment] 2018-09-26 16:53
@Bus42 The continue as guest option is already there: https://github.com/firebase/firebaseui-web#available-providers
