### ISSUE TITLE
firebase-ui-auth-1.0.0 displayName == null after Sign Up with Email provider

### ISSUE THREAD

**Issue by vitnuk** [firebase/firebaseui-web#67] opened 2016-11-13 11:44 UTC
I'm trying to use firebase-ui-auth-1.0.0 in sample app and in my app, but displayName is null after Sign Up with Email provider. You need to sign out and sign in again to actually get the displayName. Is there a way to get it working?

**Comment by TMSCH** [comment] 2016-11-13 20:14
Hi @vitnuk,
We had an issue like that in the past; however, this should have been fixed now. Could you provide a snippet of the code required to reproduce this issue? What version of the Firebase SDK are you using?
Thanks!

**Comment by Akshit94** [comment] 2016-12-16 19:01
@TMSCH I am also having the exact same problem. Is the issue fixed yet? Because I have checked my code plenty of times now but haven't been able to fixed it...please help!

**Comment by bojeil-google** [comment] 2017-01-03 20:33
Hey @Akshit94, I am unable to recreate this while creating an email and password account. Can you include details on how to recreate this?

**Comment by garyfoster** [comment] 2017-01-29 13:39
I recreated this problem by a fresh clone of the sample project this morning at  [https://github.com/firebase/FirebaseUI-iOS/tree/master/samples/swift](url). All I did was clone it, pod install, copy my GoogleService-Info.plist and run. I navigated to the auth sample, signed in via email, entered my email and password at the prompt and after the successful sign in, my display name is null, I was never prompted to enter my name. I'm not 100% certain, but I thought in the past the auth UI would prompt for name as part of the email workflow.

**Comment by thelong1EU** [comment] 2017-02-15 03:18
Me too. When user logs in with email I won't get display name.

**Comment by horak** [comment] 2017-04-07 15:34
Yeah, I'm finding the exact same thing. Oddly enough, the `user` object seems to have the right property:
![image](https://cloud.githubusercontent.com/assets/1111424/24807394/33037cde-1be2-11e7-9376-c0e50f2ece21.png)
Yet logging `user.displayName` gives me `null` which is very confusing.

**Comment by sepehragapeh** [comment] 2017-04-07 19:12
Same issue here! Login with Facebook for example has no poroblem but with email and password returns null for displayname.

**Comment by TMSCH** [comment] 2017-04-07 19:46
@horak @sepehragapeh @thelong1EU are you able to recreate the issue in the FirebaseUI demo app: https://fir-ui-demo-84a6c.firebaseapp.com/? I just tried and it worked fine (the app is using the latest FirebaseUI).

**Comment by thelong1EU** [comment] 2017-04-07 20:30
I will try tomorrow.

**Comment by sepehragapeh** [comment] 2017-04-11 16:41
It seems to be resolved, Thank you.

**Comment by Splaktar** [comment] 2017-04-27 06:02
This seems to be working for me.

**Comment by TMSCH** [comment] 2017-04-27 17:18
Thanks @Splaktar and @sepehragapeh. Closing the issue.

**Closed by TMSCH** 2017-04-27 17:18 UTC
