### ISSUE TITLE
Angular module?

### ISSUE THREAD

**Issue by drixie** [firebase/firebaseui-web#12] opened 2016-06-04 00:49 UTC
I assume this is in the works...

**Comment by tptshoe** [comment] 2016-06-05 18:47
Hi, it's not in any way official, but I've been playing around with this...

https://github.com/tptshoe/authtest

**Comment by fisherds** [comment] 2016-06-10 03:25
The problem is that the current Firebase UI shouldn't be used with a single page web app in it's current state.  Angular 2 is pretty much only for single page web apps, so you shouldn't be using the Firebase UI with Angular 2 right now. 

You can call ui.start exactly once.  So if a route calls .start, then do things that don't result in full page reloads (Angular 2 apps shouldn't really ever require a full page reload), then you can never get the UI to appear again.  So the Firebase UI is worthless in Angular 2 until that problem is addressed.

More info...
http://stackoverflow.com/questions/37413500/firebaseui-for-web-auth-how-to-re-authenticate
https://github.com/tptshoe/authtest/issues/1

Anybody tried to do the popup window solution?  Does it feel ok from a user experience?

**Comment by TMSCH** [comment] 2016-06-10 15:23
Another solution would be to redirect to the widget page, that will probably feel better on mobile. We are also working on a fix to solve this issue.

**Comment by RaphaelJenni** [comment] 2017-02-10 15:02
@fisherds I implemented it with the popup solution and a callback when the user is logged in. Works nice with AngularFire.

You can try it here: :)
https://github.com/RaphaelJenni/FirebaseUIAngularIntegration

**Comment by TMSCH** [comment] 2017-02-10 20:10
@RaphaelJenni thanks for sharing this!
@fisherds we actually implemented a `reset()` method to support Single Page App: [doc](https://github.com/firebase/firebaseui-web#tips-for-single-page-apps-ui-widget-is-already-rendered-on-the-page-warning).

**Comment by fisherds** [comment] 2017-02-11 02:55
Awesome!  Love seeing code get better and better.  I'll try things out.

**Comment by Splaktar** [comment] 2017-04-18 07:44
@RaphaelJenni thank you for the example repo! I tried the same code in my project with AngularFire2, but I just keep getting
```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

When I call `this.firebaseUiInstance = new firebaseui.auth.AuthUI(firebase.auth());`. This is odd since I've got `AngularFireModule.initializeApp(environment.firebaseConfig)` in my `app.module.ts`.

I tried calling `AngularFireModule.initializeApp(environment.firebaseConfig, [DEFAULT])` as well, but no luck.

**Comment by RaphaelJenni** [comment] 2017-04-18 08:01
@Splaktar Looking into it.

**Comment by RaphaelJenni** [comment] 2017-04-18 08:59
@Splaktar Updated demo project to the newest angular version.

With the new version you have to Inject the firebaseApp manually [Code](https://github.com/RaphaelJenni/FirebaseUIAngularIntegration/blob/master/src/app/app.component.ts#L19)

Beside that I changed requires to import.

For further questions create an issue on the project page, so everyone can see it 😄

**Comment by RaphaelJenni** [comment] 2017-04-19 16:01
@Splaktar I wrote a plugin today, which wraps the firebaseui into an angular component. You can give it a try. :) https://github.com/RaphaelJenni/firebaseui-angular

**Comment by RaphaelJenni** [comment] 2017-04-19 16:03
By the way, initializing firebase multiple times can cause some problems. Use the angularApp instance of AngularFire.

**Comment by Splaktar** [comment] 2017-04-19 18:27
@RaphaelJenni Thank you. Injecting `firebaseApp` is quite a bit cleaner than initializing it twice. I do have to make sure to use only `firebaseApp` for accessing the Firebase SDK though as any reference to `firebase.<anything>` causes the `Firebase: No Firebase App '[DEFAULT]' has been created` error to come back.

**Comment by code-tree** [comment] 2017-08-03 06:18
`reset()` method doesn't appear to work as is described in the docs. I'm getting the same errors mentioned above. Do docs need updating?

**Comment by bojeil-google** [comment] 2017-08-03 06:28
A Firebase app instance needs to be created before initializing a FirebaseUI instance. `reset` API only allows the ability to clear the UI so it can be re-rendered on a page (useful for single page apps). Both issues are unrelated.

**Comment by code-tree** [comment] 2017-08-03 09:34
Oh sorry, I probably didn't look carefully enough, as the error I was getting was probably different to above.

Instead of using an Angular service to ensure `new firebaseui.auth.AuthUI()` is only called once, I moved it into the ngOnInit method of the component holding the UI widget. Then I was calling `reset()` when the component is destroyed. But when it opened again (and called `AuthUI()` and `start()` again) I got an error message. I thought `reset()` would have prevented this.

(I've moved on now, and returned to using a service again)

**Comment by AnthonyNahas** [comment] 2018-04-04 06:48
Hey guys! I am working on many angular 5 spa pwa apps for production, which are powered by firebase for db and authentication. I had a lot of problem with this module when it comes to professional apps with server side rendering (angular universal)... like the firebaseui instance are wrong rendered .... I opened an issue and that was ignored... That's why I decided to implement an angular library with material design for firebase authentication. Please take a minute and explore my library [ngx-auth-firebaseui](https://www.npmjs.com/package/ngx-auth-firebaseui). Any feedback will be really appreciated! A live demo can be found [here](https://ngx-auth-firebaseui.firebaseapp.com)

**Comment by nicolasgarnier** [comment] 2018-08-30 14:17
Closing this, I'll send a PR to link to https://github.com/RaphaelJenni/firebaseui-angular from the README

**Closed by nicolasgarnier** 2018-08-30 14:17 UTC
Labels: priority:p3
