### ISSUE TITLE
React-firebaseui signInWithCredential failed: First argument "credential" must be a valid credential. 

### ISSUE THREAD

**Issue by samAbey** [firebase/firebaseui-web#385] opened 2018-05-09 00:33 UTC
Hellow,

I started getting below error after  signing in using google.

> signInWithCredential failed: First argument "credential" must be a valid credential.

```
"firebase": "^5.0.1",
"react-firebaseui": "^1.2.3",
```

![image](https://user-images.githubusercontent.com/32029553/39789626-a814545e-534e-11e8-80ec-f17715068987.png)

**Comment by bojeil-google** [comment] 2018-05-09 06:04
Looks like a duplicate of https://github.com/firebase/firebaseui-web/issues/367

**Comment by julientregoat** [comment] 2018-05-11 20:39
@bojeil-google in the meantime, what version should firebase be at to work with react-firebaseui?

**Comment by bojeil-google** [comment] 2018-05-11 20:56
If you are using FirebaseUI v3, you should use firebase v5 with it.

**Comment by sameeraAbeywickrama** [comment] 2018-05-12 06:43
moving from ^5.0.1  to  ^4.13.1 fixed the problem.

**Comment by rtm** [comment] 2018-06-11 12:13
My angular app give me this error after upgrading firebase to 5.0.4 and firebaseui to 3.0.0. I am now going to delve into source code and/or strip down the app to its bare bones, but meanwhile any bright ideas about things to try?

I would have just never touched this except for the fact there was a different bug in firebaseui that I was recommended to upgrade to 5.0.4 to fix. In any case it would be very hard to go back now since I have updated to the latest rc of angularfire2, which is dependent on 5.0.4, and that involved breaking changes which required code modifications.

**Comment by wti806** [comment] 2018-06-11 16:28
@rtm Are you using NPM or CDN to include firebase library? If NPM, could you use npm ls to provide your dependency list?

**Comment by rtm** [comment] 2018-06-11 17:24
@wti806 It turns out I had not fully updated my dependencies, and now things look good. Thanks for following up.

**Comment by nicolasgarnier** [comment] 2018-08-31 14:57
There was some issues here with earlier version of the Firebase SDK v5 which have now been fixed. Closing this.

**Closed by nicolasgarnier** 2018-08-31 14:57 UTC
