### ISSUE TITLE
Building FirebaseUI with localize option doesn't work.

### ISSUE THREAD

**Issue by pablocattaneo** [firebase/firebaseui-web#237] opened 2017-11-07 12:56 UTC
Hi! I run the example command _npm run build build-js-fr_ then went to _\node_modules\firebaseui\dist_ folder but there is no _firebaseui__fr.js_ file. I also runned the command using the languages es and es_419 with the same result. 
I am using :
_Windows 10 64bit_
_npm: 5.4.2_ 
_node v6.11.4_
_firebase: ^4.6.1_
_firebaseui: ^2.4.1_
_Ionic cli: 3.16.0_

**Comment by bojeil-google** [comment] 2017-11-07 18:15
This is a duplicate of https://github.com/firebase/firebaseui-web/issues/224#issuecomment-342472897
You were looking in the wrong place.

**Closed by bojeil-google** 2017-11-07 18:15 UTC
