### ISSUE TITLE
Account Chooser goes to wrong page in IE11

### ISSUE THREAD

**Issue by adelespinasse** [firebase/firebaseui-web#93] opened 2017-01-16 20:29 UTC
Internet Explorer only. I haven't tried earlier versions, just 11.

Using firebaseui-web in a pretty standard configuration. To log in with email, I click the "Sign in with email" button provided by firebaseui. It **sometimes** works the first time (i.e., have never signed in to my app with email on this browser before). If I sign out again and back in, when I click on "Sign in with email", it redirects to [What is the OpenID account chooser?](https://www.accountchooser.com/learnmore.html) instead of the actual chooser page.

Can't see what I'm doing wrong. I was using version 0.4.0, but just tried upgrading to 1.0 and it's the same. It's fine in all browsers except IE (including Edge). I'm pretty sure it used to work ok in IE11 too.

![image](https://cloud.githubusercontent.com/assets/8228772/21997865/95fb8f48-dbff-11e6-9f89-467ee14d08ec.png)

**Comment by TMSCH** [comment] 2017-01-17 18:57
Hi @adelespinasse,
Thanks for reporting this issue. I tried to reproduce it on IE 11 and Edge 14 under Windows 10, and I wasn't able. It redirects correctly to the account chooser page. Have you set any specific privacy settings in your browser? Have you tried with a clean browser? (by deleting all cache and cookies)
Thanks!

**Comment by adelespinasse** [comment] 2017-01-17 19:30
Yes, I tried deleting everything. It's hard to debug because (a) it's inconsistent, and (b) even with "clear on navigate" disabled, the IE11 developer tools disappear as soon as it gets to accountchooser.com.

Here's the entire JS code of my login page, after loading `firebase-app.js` and `firebase-auth.js` (verson 3.6.5) and `firebaseui.js` version 1.0.0 from CDN and setting keys in firebaseConfig:

      var uiConfig = {
        'signInSuccessUrl': '/',  // Ignored, but required (and can't be empty)?!
        'signInOptions': [
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.FacebookAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID
        ],
        // credentialHelper: firebaseui.auth.CredentialHelper.NONE,
        // Terms of service url.
        'tosUrl': 'https://agora.co/a/tos.html',
        siteName: "Agora Ideas"
      };

      // Initialize the FirebaseUI Widget using Firebase.
      var app = firebase.initializeApp(firebaseConfig);
      var auth = app.auth();
      var ui = new firebaseui.auth.AuthUI(auth);
      // The start method will wait until the DOM is loaded.
      ui.start('#firebaseui-auth-container', uiConfig);

For now I'm just disabling CredentialHelper. I've always thought it was a bit confusing to the user anyway.

**Comment by TMSCH** [comment] 2017-01-19 22:34
It is difficult to investigate on my end as I can't reproduce it. Is there any privacy settings (like third-party data blocked) set on the browsers?

**Comment by gbittmann** [comment] 2017-04-12 18:37
I was able to see the same error as indicated in this issue. 
Using: credentialHelper: firebaseui.auth.CredentialHelper.NONE seems to allow the email flow to work.

It is definitely broken without this setting though.  IE settings were all default, Internet Options> Advanced > Reset . . . with Delete personal settings checked.

**Comment by TMSCH** [comment] 2017-04-12 23:21
@adelespinasse was the issue you observed only on localhost or also on a deployed server?

**Comment by adelespinasse** [comment] 2017-04-13 15:58
Sorry, I don't remember. It's entirely possible that it was only on localhost. I realized that I like it better with credentialHelper set to NONE anyway, so all my servers have been configured that way ever since.

**Comment by TMSCH** [comment] 2017-04-13 16:46
Thanks for the update. Closing this bug as @gbittmann observed it would only happen on localhost, and #131 tracks the bug to address the issue.

**Closed by TMSCH** 2017-04-13 16:46 UTC

**Comment by whodidthis** [comment] 2017-04-29 18:48
Another thing that could be nice to note on README about localhost development is trying to log in using Google provider. For me it says 
`A network error has occurred.  Dismiss` 
on Firefox and 
`This browser is not supported or 3rd party cookies and data may be disabled.  Dismiss` 
on Chrome.

I assume these problems don't appear when deployed but might still catch people off guard (me).
