### ISSUE TITLE
firebase ui should require newer version of dialog-polyfill

### ISSUE THREAD

**Issue by saviski** [firebase/firebaseui-web#703] opened 2020-04-30 19:30 UTC
https://github.com/firebase/firebaseui-web/blob/60672687a7bdc95e5d253a286ba4c5a33511758a/package.json#L61

Version 0.4.7 does not export as es module

I throws an error 
'dialog-polyfill.js' does not provide an export named 'default'

v0.5.0 Ships the polyfill as an ES Module.
https://github.com/GoogleChrome/dialog-polyfill/tree/v0.5.0

reference: https://github.com/GoogleChrome/dialog-polyfill/issues/164

**Comment by JosefJezek** [comment] 2020-09-27 01:37
Duplicate of https://github.com/firebase/firebaseui-web/issues/703

**Comment by samhorlbeck** [comment] 2020-09-28 19:52
Thanks for the comment-- closing this out in favor of the earlier bug referenced by @JosefJezek

**Closed by samhorlbeck** 2020-09-28 19:52 UTC
