### ISSUE TITLE
Feature Request - Angular Intergration / Module

### ISSUE THREAD

**Issue by grahammills** [firebase/firebaseui-web#371] opened 2018-04-19 07:41 UTC
Hi,
Is there any plan to have official Angular support in Firebase UI?
I think this would be very handy in providing all the features that UI offers easily into an Angular project.
I was asked to post this here by Firebase support :-)
Thanks

**Comment by eduardocereto** [comment] 2018-07-05 06:03
Duplicate of #12

**Closed** 2018-08-31 10:40 UTC
Labels: duplicate
