### ISSUE TITLE
Improve error message if outdated authentication link is used

### ISSUE THREAD

**Issue by usu** [firebase/firebaseui-web#540] opened 2019-01-03 17:49 UTC
**Is your feature request related to a problem? Please describe.**
Sign in method EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD with forceSameDevice=true: If the user requests the sign in link to be sent multiple times and if he does not click on the latest link, a error message "new device or browser detected" is shown. This can be confusing if the user uses the same device, but just clicked on an outdated link.

**Describe the solution you'd like**
Distinguish between device/browser switching and outdated links and improve error message for outdated links, e.g. "Outdated or invalid link detected. Please make sure to use the link provided with the latest email."

**Describe alternatives you've considered*
...

**Additional context**
...

**Comment by wti806** [comment] 2019-01-03 18:15
I think "new device or browser detected" error is shown because you open the link from a different device. But you config the forceSameDevice flag to be true. An outdated link should result in a error message like this: "The action code is invalid. This can happen if the code is malformed, expired, or has already been used."

**Comment by usu** [comment] 2019-01-03 22:44
Hi @wti806 

Yes, that would be my expectation. But I do not get an "action code invalid" but always a "new device/browser detected" message.

Device/browser is definitely the same. I can reproduce consistently:
- clicking on the link in the latest email --> firebaseUI signs in properly
- clicking on the link on any previous email (outdated) or used email --> "new browser/device" message 

So if I understand you correctly, there is already an "invalid code" error message, it is just not shown in my case. Any suggestion where to start debugging?

**Comment by wti806** [comment] 2019-01-03 23:08
@usu I can confirm that when forceSameDevice flag is set to true. Wrong error message is shown to the user if the expired link is clicked. I'm still investigating the root cause and will keep you posted. Thanks!

**Comment by wti806** [comment] 2019-01-14 21:43
@usu This is fixed in [V3.5.2](https://github.com/firebase/firebaseui-web/releases/tag/v3.5.2). Thanks for reporting this issue.

**Closed by wti806** 2019-01-14 21:43 UTC
