### ISSUE TITLE
How is firebaseui supposed to be loaded, as ES module?

### ISSUE THREAD

**Issue by akauppi** [firebase/firebaseui-web#757] opened 2020-10-01 16:51 UTC
### Describe your environment

* Operating System: macOS 10.15.7
* Browser: not applicable (Chrome 85)
* Firebase UI: 4.6.1
* Firebase SDK: 7.21.1

### Describe the problem

It is not currently clear, how one can load `firebaseui` into a pure ES modules browser app. The documentation suggests this could be done, but the suggested way is at odds with the code.

1. Part A

   [Documentation](https://github.com/firebase/firebaseui-web/blob/master/README.md#option-2-npm-module) states that this should work:

   ```
   import * as firebaseui from 'firebaseui'
   ```

   However, the `esm.js` loaded by Vite (my development loader) does not have such. The `node_modules/firebaseui/dist/esm.js` file ends with:

  ```
  ...fined'){window.dialogPolyfill=dialogPolyfill;}const auth = firebaseui.auth;export { auth } ;
  ```

2. Intermission

   Before we continue, I must reveal that Firebase is loaded unconventionally as:

   ```
   import { firebase } from '@firebase/app/dist/index.esm.js'    // works; index2017.esm.js doesn't
   import '@firebase/auth'
   ...
   ```

   This works, but likely collides with FirebaseUI trying to load Firebase itself, as well.

   The reason I need to do this is that the recommended way of loading Firebase (`import * as firebase from 'firebase/app'`) does not work with Vite 1.0.0-rc.4. There are some issues open about this side with Firebase.

3. Part B

   If I try to load `firebaseui` like this:

   ```
   import { auth } from 'firebaseui'
   ```

   ..I get:
   ![](https://user-images.githubusercontent.com/1297734/94837751-53b70c80-041d-11eb-9953-1e71f839d277.png)

#### Steps to reproduce:

Have an ES modules only project (using Vite or Rollup for building). Try to bring both `firebase` and `firebaseui` in, via npm.

I'm happy to prepare a branch of my project for testing out approaches.

### Expectation from Firebase

1. Clarify what is the intended way, how FirebaseUI is supposed to be used, as an ES module.
2. Working together so that we can have both libraries loaded nicely, as ES modules. :)

### Work-arounds

I'm currently loading FirebaseUI via CDN. That works, but is against the rest of the workflow.

**Comment by akauppi** [comment] 2020-10-05 17:01
Loading `dist/esm.js` currently provides this error, in browser console:

>The requested module '/@modules/dialog-polyfill/dialog-polyfill.js' does not provide an export named 'default'

`firebaseui` [depends on](https://github.com/firebase/firebaseui-web/blob/master/package.json#L61) 0.4.7 but the [latest is](https://www.npmjs.com/package/dialog-polyfill) 0.5.3. 

Maybe a dependency update would help fix the original problem. (sorry, don't have the time to start fixing...)

**Comment by akauppi** [comment] 2020-10-05 17:07
Yes, version [0.5.0](https://github.com/GoogleChrome/dialog-polyfill/releases/tag/v0.5.0) "ships the polyfill as an ES Module."

This makes me think firebaseui might *never* have provided ES module loadability, at all. Never mind. If someone has the time & skills to update the `dialog-polyfill` dependency, things might Just Work...

**Comment by MeghaB** [comment] 2020-10-05 18:06
This is a duplicate of https://github.com/firebase/firebaseui-web/issues/674 (ES Module support). We're internally tracking modifications needed there. 

Thanks!

**Closed by MeghaB** 2020-10-05 18:06 UTC
