### ISSUE TITLE
FirebaseUI initialization takes 10 seconds on iOS Browsers (if no signed-in users)

### ISSUE THREAD

**Issue by nicolasgarnier** [firebase/firebaseui-web#57] opened 2016-09-23 14:43 UTC
It seems that Firebase-UI initialization takes a very long time (around 10 seconds) on iOS browsers (I tested Safari and Chrome) if no users are signed in.

You can test this behavior for instance on https://friendly-pix.com or on the demo app: https://fir-ui-demo-84a6c.firebaseapp.com

If a user is signed in  then the initialization is fast.

If you use the option "Request Desktop Site" of Chrome/Safari then the initialization is fast again. Truly weird stuff :)

**Comment by TMSCH** [comment] 2016-10-25 02:16
This issue was fixed in Firebase SDK release v3.5.1. It was actually not a bug of FirebaseUI but one of the underlying SDK, when running in an iOS browser, but the issue would manifest in FirebaseUI.

**Closed by TMSCH** 2016-10-25 02:16 UTC
Labels: bug
