### ISSUE TITLE
The browser you are using does not support Web Storage.

### ISSUE THREAD

**Issue by RobertoAlvarezCeballos** [firebase/firebaseui-web#68] opened 2016-11-16 11:23 UTC
Hi,

Not sure if this is expected, I thought firebaseUI-web supports most of current browsers. 

I'm testing my website in Internet Explorer 11 and I get this message as soon as I open the page. 

Any ideas?

**Comment by TMSCH** [comment] 2016-11-16 16:32
It should work, I'm able to use FirebaseUI under IE11. What version of FirebaseUI and Firebase SDK are you using? Do you have any special configuration in your browser (cookies blocked, inPrivate mode...)?

**Comment by RobertoIDL** [comment] 2016-11-21 10:26
Hi, thanks for answering. 

I managed to get it working, or at least not getting that error message. The problem is that if I try to connect using Gmail, I get the pop up window, I select my account. After a few seconds I get the message of this window is trying to close itself, I say OK. And after that nothing happens, I don't get the callback on the javascript code to change the UI.

**Comment by TMSCH** [comment] 2016-11-22 02:14
Please provide the information I asked for in my previous message so I can try figuring out with you the issue. Thanks!

**Comment by afilp** [comment] 2017-03-07 12:10
@TMSCH 
Hi, I try to use FirebaseUI to authenticate users for mobile hotspot "Captive Portals". 

However, I also get the same message "The browser you are using does not support Web Storage.".

Do CNA or other "Captive Portals" cause that issue?

**Comment by TMSCH** [comment] 2017-03-07 20:27
Hi @afilp, could I have more context on how FirebaseUI is used in your scenario? How is the app opened by the captive portal? What device/platform are you using?

It may actually be opened in some Webviews that don't support web storage, but without more information I cannot help you.

**Comment by nicolasgarnier** [comment] 2018-08-30 15:11
No Answer let's close this. Please feel free to chime in if you still experience the issue and add more details.

**Closed by nicolasgarnier** 2018-08-30 15:11 UTC
