### ISSUE TITLE
Blank widget after auth redirect

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#121] opened 2017-04-03 22:15 UTC
When a user arrives back at the FirebaseUI widget after authentication, for some period of time—sometimes multiple seconds—they see this blank rectangle with the loading animation:

<img width="723" alt="screenshot 2017-04-04 00 10 24" src="https://cloud.githubusercontent.com/assets/165223/24633898/44aa3c9e-18cb-11e7-9ea6-1b11d023c918.png">

One of my users emailed me a screenshot of this state today, thinking that I had programmed an error into my app.

I think a message should be displayed to indicate the current status or progress, or show a more ordinary loading indicator—something that a user can make sense of.

**Comment by bojeil-google** [comment] 2017-04-04 01:08
We are using the MDL progress bar: https://getmdl.io/components/#loading-section/progress
You can override the CSS to display your own GIF:
The class: .firebaseui-busy-indicator

**Comment by mhuebert** [comment] 2017-04-04 12:03
I think the non-intuitiveness may stem from the facts that 
a) this is appearing on a fresh pageload (after a redirect), rather than in an existing panel that is reacting to user input, and
b) the loader is at the top of an empty rectangle, which to an average user may look like some kind of mistake, because there is no text indicating what is happening (eg/ "Loading Account").

The most relevant [Material Design guidelines](https://material.io/guidelines/components/progress-activity.html#progress-activity-behavior) example does include a text label on the animation:
![screenshot 2017-04-04 13 56 13](https://cloud.githubusercontent.com/assets/165223/24655413/7fe7efb8-193e-11e7-93dc-e43148919bf6.png)

As does Gmail:
![screenshot 2017-04-04 13 57 46](https://cloud.githubusercontent.com/assets/165223/24655480/c32deb06-193e-11e7-8f3b-b0c547f7d18a.png)

And I would reiterate that I have received complaints from ordinary users who believed that even though this flow did sign them in to the app, there must have been an error somewhere because they interpreted the blank rectangle as some kind of mistake or error condition of the app.

**Comment by goodpic** [comment] 2017-05-18 01:24
Thanks @gbittmann for the example! It helped me to quickly fix it. I slightly modified to wrap the CSS (using SCSS) since I use mdl-shadow--2dp on the other places. 

```css
#firebaseui-auth-container {
  .firebaseui-info-bar {
    margin-top: 20px;
  }

  .mdl-shadow--2dp {
    box-shadow: none;
  }

  .mdl-progress {
    height: 5px;
  }

  div.mdl-progress::after {
    color: black;
    content: 'Authenticating';
    display: block;
    margin: 20px auto;
    text-align: center;
  }
}
```

**Comment by levithomason** [comment] 2017-06-22 05:36
### firebaseui
I think there could be an actual error here.  Using `firebaseui`, I am able to sign in (I think) but the loading state of the card never clears.  I've let this sit for several minutes in this state:

![http://g.recordit.co/bAbCbgJ10h.gif](http://g.recordit.co/bAbCbgJ10h.gif)

I say "I think" because the flow appears to indicate a successful sign in, however, the `signInSuccess` is never called.  I do not know what is going on here.

### Custom flow
Using my own auth flow, I can authenticate without issues:

![http://g.recordit.co/KPZNm89H0l.gif](http://g.recordit.co/KPZNm89H0l.gif)

**Comment by bojeil-google** [comment] 2017-06-22 07:57
Hey @levithomason can you check the browser console for errors? I tried it in our demo app https://fir-ui-demo-84a6c.firebaseapp.com but wasn't able to replicate it. It would be helpful if you can provide code snippets, environment information too to help replicate this.

**Comment by levithomason** [comment] 2017-06-22 21:39
Forgot to mention, there are no errors.  Let me see if I can whip up a minimal repro for you.

**Comment by levithomason** [comment] 2017-06-22 22:54
The minimal reproduction works.  I've tested this both with `create-react-app` and another JS compiler tool.  I've narrowed the issue down to interop with `react-redux-firebase`.  I'll investigate there a bit more and report back if I find anything.

**Comment by hasnat** [comment] 2017-08-07 21:07
@levithomason I had the same issue when using firebaseui@2.3.0 with firebase@3.7.0
updating firebase to 4.2.0 fixed the issue for me

**Comment by levithomason** [comment] 2017-08-09 05:55
The infinite loading issue seems to have been resolved here as well.  Running these versions:

`firebase` `^4.2.0`
`firebaseui` `^2.3.0`

`react` `^15.5.4`
`redux` `^3.6.0`
`react-redux` `^5.0.5`
`react-redux-firebase` `2.0.0-beta.4`

**Comment by carlosazaustre** [comment] 2017-10-08 14:54
With `firebase 4.5.0` and `firebaseui 2.4.0` this issue is back :(

**Comment by bojeil-google** [comment] 2017-10-09 03:22
Hey @carlosazaustre, I don't think we made any changes to affect this behavior.
Can you check for any errors in the browser console? and provide them.

**Comment by levithomason** [comment] 2017-10-09 16:43
I've simply switched to a custom flow.  Much easier to control and know what is going on.

**Comment by carlosazaustre** [comment] 2017-10-13 08:42
@bojeil-google sorry, console shows anything, simply the browser shows a infinite loading bar, just like @mhuebert comments.

**Comment by bojeil-google** [comment] 2017-10-13 17:32
Something must be hanging. Can you inspect the network console for some request that is hanging or erroring? Also does this happen consistently? or occasionally?
If you can host this somewhere, it will make it a lot easier to debug.

**Comment by Ghosts** [comment] 2017-10-17 02:28
Not sure if this will help anyone else, but whenever I got the "infinite" loading issue I would clear Local Storage - specifically:
`firebaseui::rememberedAccounts`

I've written it into the "signout" method I have to also clear local storage / that key.

I'm using 2.4.0 of Firebase-ui.

**Comment by deckarep** [comment] 2017-11-27 03:41
Also experiencing this ugly white box...it just straight up looks broken during this intermediate step.

**Comment by bojeil-google** [comment] 2017-11-27 08:32
The display is optimized for a mobile device with no surrounding container. You can completely remove that box with css overrides:
```
.mdl-shadow--2dp {
  box-shadow: none
}
```

**Comment by berkayturanci** [comment] 2017-12-21 19:09
For removing the ugly white box;

`.firebaseui-id-page-callback {
            background: none !important;
        }`

**Comment by lecstor** [comment] 2018-04-25 12:33
when I finally realised my background wasn't quite white..
this worked for me to shrink the box down to the height of the spinner.. not sure that there's never content that might hide though.
```
.mdl-card .firebaseui-callback-indicator-container {
  height: 2px;
}

.mdl-card.firebaseui-container {
  min-height: 2px;
}
```

**Comment by deepfriedbrain** [comment] 2018-06-18 23:50
I'm in the process of switching from Google Identity Toolkit and landed here because of the same issue. The default implementation definitely looks broken and that's what brought me here. Given that it hasn't been changed in over a year, I was wondering if there's any good reason to keep it this way.

**Comment by nicolasgarnier** [comment] 2018-08-30 20:27
Let's close this issue since it was initially about styling of the "loading screen" after a successful sign-in when using the redirect flow.

https://github.com/firebase/firebaseui-web/issues/121#issuecomment-293913917 provides a way to customise this UI and add a text to your liking.

For other issues, especially if you are reporting a never ending loading screen please open a new issue.

**Closed by nicolasgarnier** 2018-08-30 20:27 UTC

**Comment by jxc876** [comment] 2019-12-29 05:59
Wish this was documented on the main README. Was really confused by there was an empty box, the user experience is greatly improved with the CSS from above.

**Comment by Danebrouwer97** [comment] 2020-09-01 15:31
@nicolasgarnier I'm really curious about this issue, how is a large empty white box with a loader attached to the top an appropriate solution?

Is there any documentation surrounding the Loading UI, or how to change it, or even that there is a large white box attached to the loader?

I realize that [#121 (comment)](https://github.com/firebase/firebaseui-web/issues/121#issuecomment-293913917) solves the problem, but it seems curious that this is still an issue almost 4 years later.
