### ISSUE TITLE
"'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016"

### ISSUE THREAD

**Issue by mesotron** [firebase/firebaseui-web#60] opened 2016-10-15 09:58 UTC
Chrome has been giving me the following warning with respect to line 70 of firebase-ui-auth for some time now:

'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

Are there plans to address this soon? Thanks.

**Comment by TMSCH** [comment] 2016-10-17 20:07
Hi,

Thanks for notifying us!

I was not able to reproduce it with my config: I don't get any warnings on the FirebaseUI demo app (https://fir-ui-demo-84a6c.firebaseapp.com/) with the latest version of Chrome on Mac: **Version 54.0.2840.59 (64-bit)**. I also tried the following version on Mac: **Version 53.0.2785.116 (64-bit)** and **53.0.2785.143 (64-bit)** on Ubuntu.

Could you let me know if you observe the same issue in the FirebaseUI demo app too? What is your platform and chrome version?

**Comment by mesotron** [comment] 2016-10-18 09:05
Yes, I also get this warning on the FirebaseUI demo app, after selecting Sign In With Email and typing into either the "First & last name" field or the "Choose password" field that comes up when I am prompted to create an account. Warning is still for firebase-ui-auth.js line 70. 

I am using the latest version of Chrome (Version 54.0.2840.59 m) on an up-to-date version of Windows 10 (64-bit), though I noticed this warning well before Chrome v54, so I suspect it affects earlier versions as well.

By the way, the demo app also throws two errors on this configuration, but they don't seem to impede my ability to create an account and sign in. I've included these below in case it helps.

-----------------
Upon clicking Sign in with Email for the first time:

"X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>." redirect.html#fir-ui-demo-84a6c.firebaseapp.com:11

and one just before I am prompted with the "Sign in" screen in Single Page Application Mode:

jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://fir-ui-demo-84a6c.firebaseapp.com" from accessing a cross-origin frame.
at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)

**Comment by TMSCH** [comment] 2016-10-18 17:02
Thanks for the further details! I was indeed able to reproduce it on Windows. It appears OS X and Linux work fine. We will look into this to fix the issue.

As for the other errors, I was able to observer the first one (X-Frame-Options) and it seems to come from accountchooser.com. I will see if we can do anything about it, but as you said, it doesn't seem to prevent users from signing in.
I haven't observed the last one though, but looking at the stack trace, it seems to come from a chrome-extension.
Could you go to the internal chrome url: `chrome://extensions/` and look for an extension with ID: `laankejkbhbdhmipfmgcngdelahlfoji`? It may give us a better understanding of what is happening.

**Comment by TMSCH** [comment] 2016-10-18 21:49
The bug on`KeyboardEvent.keyIdentifier` has been fixed and will be released as part of the 1.0.0 release.

**Comment by mesotron** [comment] 2016-10-19 15:52
Many thanks!

I'm not concerned about the error thrown by the chrome extension, but the offending extension appears to be StayFocusd ( https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji?hl=en ). I've included the full stack trace below.

-------
jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://fir-ui-demo-84a6c.firebaseapp.com" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)contents @ jquery.min.js:2map @ jquery.min.js:1ot.fn.(anonymous function) @ jquery.min.js:2(anonymous function) @ ActivityMonitorOverlayView.js:1each @ jquery.min.js:1each @ jquery.min.js:1bindActivityDetectors @ ActivityMonitorOverlayView.js:1init @ ActivityMonitorController.js:1onLoaded @ content.js:1(anonymous function) @ ComponentFactory.js:1execCb @ cajon.js:1check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1emit @ cajon.js:1check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1emit @ cajon.js:1check @ cajon.js:1enable @ cajon.js:1init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1emit @ cajon.js:1check @ cajon.js:1enable @ cajon.js:1init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1finishLoad @ text.js:1(anonymous function) @ text.js:1a.onreadystatechange @ text.js:1

**Comment by TMSCH** [comment] 2016-10-19 16:45
I would also ignore the error from the chrome extension.

As far as the `X-Frame-Options` is concerned, it won't have any impact on your usage of FirebaseUI. I'll try to see why accountchooser.com does use this option in a meta tag, maybe they can remove it.

**Comment by TMSCH** [comment] 2016-11-08 23:11
This should be fixed now. I have tested under Windows and Chrome M54 and the error is not raised anymore. @mesotron would you like to confirm this before I close the issue?

Thanks!

**Comment by mesotron** [comment] 2016-11-09 11:59
Yes, I confirm. Thanks very much!

**Comment by TMSCH** [comment] 2016-11-09 17:45
You're welcome!

**Closed by TMSCH** 2016-11-09 17:45 UTC
