### ISSUE TITLE
disallow/disable auto sign up

### ISSUE THREAD

**Issue by rubenslopes** [firebase/firebaseui-web#546] opened 2019-01-12 19:22 UTC
my app is only for known users,

a config to disable this behavior would be nice

**Comment by buzzware** [comment] 2019-06-17 01:34
Duplicate of #99

**Comment by jhuleatt** [comment] 2023-07-20 19:23
#99 has been fixed: https://github.com/firebase/firebaseui-web/issues/99#issuecomment-794537000

**Closed by jhuleatt** 2023-07-20 19:23 UTC
