### ISSUE TITLE
add to home screen apps get stuck at redirect on android

### ISSUE THREAD

**Issue by ptone** [firebase/firebaseui-web#247] opened 2017-11-19 21:34 UTC
When using "Add to Home screen" feature in Android, Google login flow gets stuck on a url like:

[appURL]/__/auth/handler?state=[blah]

You can reproduce this pretty easily by going to:

https://fir-ui-demo-84a6c.firebaseapp.com

in Android Chrome - select "add to home screen"

Then launch the demo from homescreen, choose sign in with redirect - and try to login with Google

**Comment by bojeil-google** [comment] 2017-11-20 05:05
This looks like it is related to the Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=771418#c12
It is a also a duplicate of https://github.com/firebase/firebaseui-web/issues/221

**Comment by JasonMuteham** [comment] 2018-02-24 14:49
As this bug breaks firebase authentication with PWA and has been an issue for months could we update read.me known issues?

The suggested signInFlow: "popup"  workaround does not appear to work (anymore?). My webapp used this signInFlow and got caught by this bug.  However, I do have a workaround.

## The problem.

in Android Chrome - select "add to home screen"

Chrome will either - 

1. If the PWA does **NOT** meet googles [requirements](https://developers.google.com/web/fundamentals/app-install-banners/) for "app install banners" only a shortcut to the app will be added to the home screen.  It will  use manifest.json file for the config.  Your PWA will authenticate as expected.  _Happiness._
### or
2. If the PWA **DOES** meet the "app install banners" requirement chrome will download a APK to install on the home screen, more infor [here](https://developers.google.com/web/updates/2017/02/improved-add-to-home-screen).  This will break authentication, as the APK reduces the PWA scope.  _Sadness._

## Workarounds.
All the workarounds involve making the PWA **NOT** meet the requirements for "app install banners" so the APK is not downloaded and a shortcut icon is created instead, the negative effect of this is **no** auto prompting of chrome to install the app to the home screen.

Option 1.  If a service worker is not required, remove it.
### or
Option 2.  If a service worker is required, then alter the manifest.json so it fails the requirement but is still useful.  I removed the configuration for icons 144x144 and above in the manifest.json.  This may cause the PWA splash screen to have no icon.

I hope this helps.  

This is my first post of this type so if this is the wrong place for this info please point me to a better place.  

Thanks.

**Closed** 2018-08-31 01:04 UTC
Labels: duplicate
