### ISSUE TITLE
An option to force UI to be either "sign up" only or "log in" only

### ISSUE THREAD

**Issue by ArtemBogush** [firebase/firebaseui-web#499] opened 2018-09-05 12:04 UTC
After using FirebaseUI in our Chrome extension for a while we've noticed the following UX issue with the automatic switching of the signup/login flows:

When user created an account and they want to login again, they might spell their email incorrectly or mistakenly put their other email - often times when that happens they don't notice that and they end up creating a new account without realizing that (even though the popup says "create account", this is not what they notice since they just login again and as the flow allows them to get through, everything looks fine to them)

This leads to confusion and in some extreme case it already lead to a situation when a user paid twice under different accounts and after realizing the fact that "we've charged them twice for the same product", they asked for a full refund for the both accounts.

I'm wondering if there is a way to lock "sign up" flow so it will always show "Create an account" by default and in order for them to login, they have to explicitly press a link like "Already have an account? Log in here" which will then switch to the "log in" flow.

Any input on that is much appreciated!

**Comment by ArtemBogush** [comment] 2018-09-10 13:50
Just got another 3 claims from users on the same matter for the last few days. Would really appreciate any input on this.

**Comment by bojeil-google** [comment] 2018-09-10 18:01
We don't support separate sign-up/sign-in flows. Supporting this would require some non-trivial UX re-design (we also abstract sign-in/sign-up for OAuth sign-in and phone number sign-in). It is unlikely to happen in the short term. We already have features planned for next couple of months.

**Comment by dandv** [comment] 2018-09-24 23:06
If I'm correct in my last comment on #99, then this issue seems like a dupe of #99.

**Comment by nicolasgarnier** [comment] 2018-09-25 18:12
Thanks @dandv, yes this is a duplicate of #99. Closing :)

**Closed by nicolasgarnier** 2018-09-25 18:12 UTC
Labels: duplicate, feature:auth

**Comment by ArtemBogush** [comment] 2018-09-26 00:28
@NickChittle  I'm not sure this is a duplicate actually as the core of our issue is that we still need to provide both sign in and sign up flows but they shouldn't switch automatically as this leads to confusion. Though probably this cold be easily programmed outside firebseUI once there is a separated flows for sing in and sing up so it's possible to choose from code which form to show. 

But as long as this can be provided within the scope of #99, I guess that's ok to close this one.
